### PR TITLE
don't check style on bin/*

### LINKED ISSUE #31: /bin should be excluded from all cops by default
I know this was a question that @alexdean had posed and chose to leave the cops enabled for the rails `/bin` directory.

I believe however, that we (at least I) rarely write custom code in this directory and will have to end up cleaning up the generated files to fit our styles.

A generic rails app fails our rubocop linting as follows:

```
bin/setup:5:51: C: Unnecessary spacing detected.
APP_ROOT = Pathname.new File.expand_path('../../',  __FILE__)
                                                  ^
bin/setup:11:8: C: Prefer single-quoted strings when you don't need string interpolation or special symbols.
  puts "== Installing dependencies =="
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
bin/setup:12:10: C: Prefer single-quoted strings when you don't need string interpolation or special symbols.
  system "gem install bundler --conservative"
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
bin/setup:13:10: C: Prefer single-quoted strings when you don't need string interpolation or special symbols.
  system "bundle check || bundle install"
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
bin/setup:21:10: C: Prefer single-quoted strings when you don't need string interpolation or special symbols.
  system "bin/rake db:setup"
         ^^^^^^^^^^^^^^^^^^^
bin/setup:24:10: C: Prefer single-quoted strings when you don't need string interpolation or special symbols.
  system "rm -f log/*"
         ^^^^^^^^^^^^^
bin/setup:25:10: C: Prefer single-quoted strings when you don't need string interpolation or special symbols.
  system "rm -rf tmp/cache"
         ^^^^^^^^^^^^^^^^^^
bin/setup:28:10: C: Prefer single-quoted strings when you don't need string interpolation or special symbols.
  system "touch tmp/restart.txt"
         ^^^^^^^^^^^^^^^^^^^^^^^
bin/spring:11:101: C: Line is too long. [101/100]
    Gem.paths = { 'GEM_PATH' => [Bundler.bundle_path.to_s, *Gem.path].uniq.join(Gem.path_separator) }
```

I'd like to add the following to our rubocop.yml:

```
# don't check style on generated files.
AllCops:
  Exclude:
    - 'tmp/**/*'
    - 'db/schema.rb'
    - 'bin/**/*'
```

### PR DESCRIPTION
**Pull request by alexdean**
we think these are 99% generated files (like bundler binstubs)

@tedconf/backenders any objections?

closes #31

### CODE REVIEW

**Comment by jwarchol** [comment]
Motion to merge. I yield the remainder of my time to the gentleman from South Dakota

**Comment by alexdean** [comment]
@jwarchol thanks for the reminder. i was waiting for feedback, but just realized that GH doesn't send notices when people add reactions.

**Comment by jwarchol** [comment]
Huh. That's good to know. I thought it would have told you. 

I guess on one hand I can see them not wanting to send a bunch of "Josh said thumbs up" emails. On the other, how do you know there has been any? Hmmm. 

In the future I'll comment so it's clearer.

**Comment by alexdean** [comment]
yeah, i agree on all counts. i wouldn't want an email notification for a thumbs up either.

i suppose it's good practice to plan on checking in on PRs we've opened, just to check for this kind of activity.

**Comment by jwarchol** [comment]
Reactions seem intended for simply expressing feeling, but not contributing to a conversation as such. I'll keep my use of them to that. Got a bit excited about the new feature! 

I don't want people to miss out on the :heart:

**Pull request merged**
