### PR TITLE
Display cop names by default

### PR DESCRIPTION
**Pull request by griley**
I find it very useful to have the cop names output along with the offense.

### CODE REVIEW

**Comment by danbernier** [comment]
This is great! I just learned the `rubocop -f o` incantation recently, which displays the cop names with their violation counts, but this is even better.

**Comment by alexdean** [comment]
let's give @tedconf/backenders a day or two to weigh in on any reasons we might not want to do this. after that, i say ship it.

**Comment by alexdean** [comment]
@danbernier `-f o` TIL. thanks! i've wanted a display like this many times, and didn't realize it was already available.

docs aren't exactly clear.

```
$ rubocop --help

    -f, --format FORMATTER           Choose an output formatter. This option
                                     can be specified multiple times to enable
                                     multiple formatters at the same time.
                                       [p]rogress (default)
                                       [s]imple
                                       [c]lang
                                       [d]isabled cops via inline comments
                                       [fu]ubar
                                       [e]macs
                                       [j]son
                                       [h]tml
                                       [fi]les
                                       [o]ffenses
                                       [w]orst
                                       custom formatter class name
```

**Comment by danbernier** [comment]
@alexdean yw! No, the docs are not clear. I stumbled into it accidentally, or by brute force, I can't remember which. Either way, it was a rough night.

**Comment by jhirbour** [comment]
I like having the cop names displayed. Easier to batch fix them.

**Pull request merged**
