### PR TITLE
allow methods of up to 25 lines

### PR DESCRIPTION
**Pull request by alexdean**
@tedconf/backenders this is a question as much as a PR...

i get that we don't want hundred-line methods. that said, a 10-line limit feels overly-restrictive to me. i've tried to refactor to this limit several times and ended up feeling like the result was actually harder to understand.

  1. more context switches are required to follow one logical operation through multiple short methods
  1. requires artificially-named methods, for these methods which are only single-use and exist only to be short.
  1. lots of these tiny methods pollute the class api and make it harder to understand. (you can sorta mitigate this by making all those teensy methods private, but then you can't test them.)

all this is just to say i know there's such a thing as too long, but after trying multiple times i'm also convinced there's such a thing as too short - and 10 lines feels too short sometimes.

i'm open to picking another limit if anyone wants to suggest one.

  1. not less than 15-20
  1. not more than 50

opinions? 25 feels pretty ok to me.

### CODE REVIEW

**Comment by DanielRussell** [comment]
I'd love to run an experiment across our whole codebase with N = {10, 25, 50, 100}.

Goal is to make a "how much work will we sign ourselves up for if we choose X?"  This would generate one input into the decision -- I'm not suggesting we look for the knee of the curve and pick that without thinking.

**Comment by alexdean** [comment]
> I'd love to run an experiment across our whole codebase with N = {10, 25, 50, 100}.

I think the goal here is to make a best-effort guess about "what's a reasonable upper limit / big O on method length in the normal case?".  As in, we're trying to find "methods longer than this are very likely too long".

I think it's clear we're shooting at a hazy target. It's probably possible to write a longer method which is readable & well-focused, just as it's possible to write a shorter method which does too much.

>  I'm not suggesting we look for the knee of the curve and pick that without thinking.

@DanielRussell If I understand correctly, you're saying that current code won't tell us what we ought to do, but it can tell us how much work we're taking on by choosing a given limit. (Comparing to current code is informative but not normative.)

Let me know if I've incorrectly mansplained you.

**Comment by griley** [comment]
10 is a _ridiculous_ number for the reason Alex stated...

>  i've tried to refactor to this limit several times and ended up feeling like the result was actually harder to understand.

I'm OK with 25 for sure, but I would object to 30 either.

**Comment by alexdean** [comment]
i'm merging this tomorrow sometime unless i hear objections.

**Comment by CpuID** [comment]
Seems legit, this will force me to at least keep sane length methods which is a good thing.

**Comment by mtwentyman** [comment]
For the vast majority of the cases, this has pushed toward more testable, readable code.  Is there an example that disproves this?

**Comment by jwarchol** [comment]
I think "vast majority of cases" deserves examples more than saying one arbitrary, relatively small limit is objectively better than another. If 25 means most of our code passes and 10 means we'd have to rewrite a huge amount for little gain, it's a waste of time. Apologies for blunt-ness, I don't have high regard for exceptionally strict linting limits.

**Comment by alexdean** [comment]
@mtwentyman i don't think we're taking about something that's provable one way or another.

In my view, rubocop should be there to point out things which are clearly problematic. **So in this case, I think we should be looking for a value which is an upper bound on reasonable method length.** When in doubt, it should be quiet & let humans use their judgement.

**Question for everybody**: Do you agree on this, or do you see the purpose of rubocop differently?

I've been an advocate for rubocop because I like the idea of converging on a common style - but I don't want to be tapped on the shoulder every few minutes because maybe it's possible I could do things differently. The more restrictive we write our rules, the more incentive we create for people to subvert the rules with local exceptions - thus lessening the value of the whole exercise.

That said, the value of a style guide is proportional to the number of people who really buy in to it. If the global guide says one thing, but people litter their projects with individual exceptions to rules they don't agree with, the global guide isn't much use.

So... this is a good conversation to have! Let's build some consensus. I'm in no rush to merge this change as long as there's more discussion to be had.

**Comment by alexdean** [comment]
Here's [one example](https://github.com/tedconf/trails/blob/cc8dbc803243d0e8f26a97ecac5f9e4c7f9bd5c8/app/concerns/trails/status_error.rb#L82-L90) of a method I've written recently (& actually was the final straw that led to this PR).

This method is dumb. It only exists to make `.factory` shorter. `.factory` would not be less readable or testable if `_handle_symbol_code` were just inline code rather than a separate method. Of course we can disagree here. You might think this method is perfectly fine. And truth be told I don't think it's the end of the world by any means.

I'm sure I could find other examples, just as I could find examples of 15-line methods which would be better as 2 shorter methods. The point to me is how often do we want the tool to speak up, & imo the standard should be "when in doubt, hush".

**Comment by mtwentyman** [comment]
My concern is that if you start bumping the limits up on this and the other restrictions together that you'll have a less meaningful tool to catch the ugly happening.  Personally, I bought into rubocop precisely because the defaults were good enough and agreed upon by more than just us.

That said, CI isn't a reason to not do code reviews, so hopefully this makes a net positive change for all.

**Pull request merged**
