### PR TITLE
lib folder

### PR DESCRIPTION
**Pull request by samselikoff**

### CODE REVIEW

**Comment by samselikoff** [comment]
needs review

**Comment by brenna** [comment]
ok to merge by me. @ryanto ?

**Comment by ryanto** [comment]
The lib stuff is good, but I think {{each}} blocks should always only render a row/item component. Reasoning here is these things tend to grow pretty quickly, and there's often a bunch of hacks you can do to put off the item level component, but that could be unwieldy to other developers.

**Comment by samselikoff** [comment]
I'm down with that

**Pull request merged**
