### PR TITLE
Ruby 2021 update plan

### PR DESCRIPTION
**Pull request by jhirbour**

### CODE REVIEW

**Comment by jhirbour** [comment]
@caomania I'm able to produce the data I think we need for this project. Can you peak at these columns and see if there's anything you'd like to add. Obviously I'll dump the final output into a sheet. Just checking for columns now.

**Comment by caomania** [comment]
Thanks  @jhirbour this is great these columns look correct to me. 
Question about the `bundler_version` column, what version is '1-glm-added'?

**Comment by jhirbour** [comment]
@caomania that nasty tid bit is a purposefully ugly version string. The nasty details are:  GLM is running bundler 1 so it can't parse bundler 2 files. So [here](https://github.com/tedconf/git_lumber_mill/pull/41/files#diff-f6dee4b28223cf3c3227b1f507deaa1b221f88aae8982471837ca441c8b68bc1R252-R277) where we populate the gems listed we're fudging that the bundler version .  This code would need to change for bundler 2 obviously. Also bundler 2 actually lets you introspec the version easily.

**Comment by jhirbour** [comment]
Updated data:

**Comment by jhirbour** [comment]
After [This PR](https://github.com/tedconf/git_lumber_mill/pull/41) is merged the data above and query will work on GLM production.

**Comment by jhirbour** [comment]
I've added columns to the report SQL for all the gems that TED (has in our github repos with gemspec files). This is list is likely pretty accurate (RE the list of what is a gem). 

Example row displayed vertically (using \G)

**Comment by alexdean** [comment]
hey dudes heads up this is a public repo & public PR.

**Pull request closed without merging**
